"""Initial migration.

Revision ID: 1d3455b12b40
Revises: 
Create Date: 2024-05-08 17:21:15.337437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3455b12b40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gameName', sa.String(length=20), nullable=False),
    sa.Column('secondGameName', sa.String(length=20), nullable=False),
    sa.Column('creator', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('dlc', sa.Boolean(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('ageGroup', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creator'),
    sa.UniqueConstraint('gameName'),
    sa.UniqueConstraint('secondGameName')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('age', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', 'age'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('games')
    # ### end Alembic commands ###
