"""Initial migration.

Revision ID: 52ce401d93dc
Revises: 
Create Date: 2024-06-12 16:39:55.976680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ce401d93dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publisher', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('imageBanner', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('videoPromotional', sa.String(length=200), nullable=True))
        batch_op.alter_column('creator',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=15),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.drop_constraint('games_creator_key', type_='unique')
        batch_op.drop_constraint('games_gameName_key', type_='unique')
        batch_op.drop_constraint('games_secondGameName_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_unique_constraint('games_secondGameName_key', ['secondGameName'])
        batch_op.create_unique_constraint('games_gameName_key', ['gameName'])
        batch_op.create_unique_constraint('games_creator_key', ['creator'])
        batch_op.alter_column('description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.String(length=15),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('creator',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('videoPromotional')
        batch_op.drop_column('imageBanner')
        batch_op.drop_column('publisher')

    # ### end Alembic commands ###
